## **Loading and Printing Data**

In [4]:
#importing the csv file
import pandas as pd
csv1 = pd.read_csv('Combined_dataset.csv')
csv1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

## **2.Exploring data**

In [57]:
csv2 = pd.read_csv('Combined_dataset.csv')
csv2.head()
#display first 5 values

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [56]:
csv3 = pd.read_csv('Combined_dataset.csv')
csv3.tail()
#only last 5 values

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [7]:
csv1.shape

(1000, 24)

In [8]:
csv4 = pd.read_csv('Combined_dataset.csv',nrows=60)
csv4 #displaying selective rows

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
10,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sig███Ove███as,"[{""size"":""Super King""}]",NaN,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",NaN,E-1███103███PIP█████████ IN███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
13,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
14,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
15,19788630,Home Ecstasy,140tc Pure Cotton printed Teal Blue Single Bed...,4.5,6,1199,42.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/197...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
16,20296382,DREAM WEAVERZ,Grey & Coral Printed 220 TC Glazed Cotton King...,3.8,18,2599,78.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/202...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Double Queen""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
17,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329,76.0,"""₹6,329.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",NaN,A-5███ADA███R V█████████ De█████████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts
19,18985918,Tommy Hilfiger,Women Navy Blue Embroidered High-Neck Pure Cot...,4.1,11,2999,40.0,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""XXS"",""value"":""21.8in"",""value_name"":""...",NaN,PVH███vin███ash█████████tdN███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit
20,22120138,Ed-a-Mamma Baby,Infant Boys Pack Of 2 Printed Pure Cotton Body...,4.2,5,999,30.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,ETE███LIA███EAT█████████CHA███████████████████...,"[{""size"":""0-3M"",""value"":""18.9in"",""value_name"":...",NaN,1A ███I H███E S█████████CH ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit
21,1728397,Mactree,Men Brown Solid Mid-Top Flat Boots,3.9,1727,9060,88.0,"""₹1,087.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":228,""2_stars"":89,""3_stars"":186,""4_st...",NaN,MAX███ IN███NAT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",NaN,"21/███10 ███NS █████████4 ,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.0,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",NaN,SAI███USE███OT █████████ NA███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
23,17372928,The Souled Store,Men Blue & White Abstract Printed Boxers,4.5,22,799,54.0,"""₹367.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",THE███ULE███TOR█████████D.,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",NaN,"F6 ███02,███umi█████████dus███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boxers
24,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579,NaN,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":90,""2_stars"":25,""3_stars"":93,""4_star...",NaN,Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...",NaN,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
25,22063882,GROVERSONS Paris Beauty,Non Padded Cotton Seamless Non-Wired T-shirt Bra,4.0,25,399,25.0,"""₹299.00""",INR,http://assets.myntassets.com/assets/images/220...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,Gro███son███ppa█████████Ltd███,"[{""size"":""30B"",""value"":""31.0in"",""value_name"":""...",NaN,"sec███ A-███Plo█████████, I███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
26,19219450,Susie,Black Solid Cotton T-Shirt Bra - Anti-Odour,4.3,12,749,50.0,"""₹374.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,GEN███AD ███AIL█████████LIM██████,"[{""size"":""30B"",""value"":""31.0in to 32.0in"",""val...",NaN,2ND███OOR███O 1█████████MAL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
27,22196924,Zivame,Underwired Lightly Padded Pushup Bra,4.3,118,999,50.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":6,""2_stars"":7,""3_stars"":8,""4_stars"":...",NaN,MIL███AR ███AIL█████████LIM██████,"[{""size"":""30A"",""value"":""31.0in"",""value_name"":""...",NaN,MIL███TAR███TAI█████████ LI███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
28,19219468,Susie,Women Black Solid Everyday Cotton Bra,4.0,6,699,43.0,"""₹398.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,GEN███AD ███AIL█████████LIM██████,"[{""size"":""32B"",""value"":""33.0in to 34.0in"",""val...",NaN,2ND███OOR███O 1█████████MAL███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
29,22278620,Tweens,Pack Of 2 Non Padded Medium Support All Day Co...,0.0,0,720,16.0,"""₹604.00""",INR,http://assets.myntassets.com/assets/images/222...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bel███Lin███ies█████████.,"[{""size"":""30B"",""value"":""31.0in"",""value_name"":""...",NaN,B-5███Roo███aga█████████al ███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
30,19277544,Marks & Spencer,BOUTIQUE X DAMARIS Navy Blue Underwired Lightl...,4.3,24,2999,60.0,"""₹2,249.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":4,""4_stars"":...",NaN,Ret███Net███,"[{""size"":""32B"",""value"":""34.0in"",""value_name"":""...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
31,18223842,max,Plus Size Non Padded Bra,4.1,37,449,20.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":4,""4_stars"":...",NaN,NaN,"[{""size"":""40B"",""value"":""42.0in"",""value_name"":""...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bra
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,NaN,"""₹345.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",NaN,VI/███ AB███ ST█████████ODE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
33,18656764,VStar,Grey Solid T-Shirt Bra,4.3,6,345,NaN,"""₹345.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",NaN,VI/███ AB███ ST█████████ODE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
34,13523458,shyaway,Multicoloured Set of 3 Printed Underwired Ligh...,4.3,6,2547,52.0,"""₹2,547.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""32B"",""value"":""33.46in to 33.85in"",""v...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bra
35,18652628,max,Sea Green & Blue Floral Bra Lightly Padded SU2...,4.2,5,649,20.0,"""₹649.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""30B"",""value"":""32.0in"",""value_name"":""...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bra
36,17774350,Zivame,Pink Lightly Padded T-shirt Bra,4.2,9,995,50.0,"""₹995.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""32B"",""value"":""33.8in"",""value_name"":""...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bra
37,16704504,ZINU,Women Silver-Toned Brass Cubic Zirconia Rhodiu...,4.1,7,699,45.0,"""₹384.00""",INR,http://assets.myntassets.com/assets/images/167...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,SAN███UNE███,"[{""size"":""Onesize"",""value"":""7.0in"",""value_name...",NaN,BLD███NO.███BAS█████████VAI███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.0,"""₹815.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",NaN,Sho███58-███Sec█████████ain███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
39,21573578,Jewels Galaxy,Women Brass Gold-Plated Bangle-Style Bracelet,4.2,24,1329,77.0,"""₹305.00""",INR,http://assets.myntassets.com/assets/images/215...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,RS ███els███,"[{""size"":""Onesize"",""value"":""2.38in"",""value_nam...",NaN,"9/1███, S███et █████████ula███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
40,18100576,MINUTIAE,Women Gold-Toned & White Brass Crystals Handcr...,3.2,13,1499,70.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/181...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""6.5in"",""value_name"":""Cir...","[""rw-18100576_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bracelet
41,18532334,Pepe Jeans,Men Green Printed Cotton Basic Briefs,0.0,0,459,20.0,"""₹298.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",NaN,3rd███oor███o. █████████Mai███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
42,16696094,Van Heusen,Men Swift Dry High Stretch Mesh AIR Series Act...,4.6,192,649,NaN,"""₹649.00""",INR,http://assets.myntassets.com/assets/images/166...,...,"{""1_star"":8,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",NaN,"Gro███ Fl███, N█████████old███████████████████...","[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
43,21867416,DressBerry,Women Boy Shorts Brief,4.1,14,299,28.0,"""₹215.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,VAC███CRE███ONS███,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",NaN,"870███TRE███SHE█████████, B███████████████████...","[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
44,21850852,Soie,Women High Waist Full Coverage Lace Brief,4.9,14,390,5.0,"""₹370.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,GIN███IND███RIE█████████,"[{""size"":""S"",""value"":""26.4in to 28.7in"",""value...",NaN,Plo███o B███9-3█████████oor███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs

In [9]:
csv5 = pd.read_csv('Combined_dataset.csv',usecols=[3,4])
csv5 #displaying selective columns

     rating  ratings_count
0       3.8             15
1       4.5             67
2       4.4            226
3       4.4           1052
4       4.7             12
..      ...            ...
995     3.5             11
996     5.0             22
997     2.8              5
998     4.3             17
999     3.8            161

[1000 rows x 2 columns]

In [10]:
csv6 = pd.read_csv('Combined_dataset.csv',skiprows=[5,6,2])
csv6 #skipping selected rows

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
4,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
993,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
994,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
995,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
996,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [11]:
csv7 = pd.read_csv('Combined_dataset.csv',index_col='title')
csv7 #changing index

,product_id,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
title,,,,,,,,,,,,,,,,,,,,,
Lino Perros,8376765,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
Tommy Hilfiger,9136281,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
Lavie,17633752,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
F Gear,1376949,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
MYTRIDENT,13939916,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KREDO,13698258,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
GUESS,16896006,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
GIORDANO,1708108,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
Fastrack,19280114,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
BOLDFIT,18601682,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [55]:
csv7 ['rating']=csv7['rating'].astype(int)
csv7
#converting rating column values as int

,product_id,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
title,,,,,,,,,,,,,,,,,,,,,
Lino Perros,8376765,Women Navy Blue Solid Backpack,3,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
Tommy Hilfiger,9136281,Unisex Navy Blue Striped Backpack,4,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
Lavie,17633752,Aries Women Pink Mini Backpack,4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
F Gear,1376949,Unisex Navy & Grey Printed Burner Backpack,4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
MYTRIDENT,13939916,Men Blue Solid Bath Robe,4,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KREDO,13698258,Men FORTE Silver Automatic Skeleton Analogue W...,3,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
GUESS,16896006,Women White Patterned Dial & White Straps Anal...,5,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
GIORDANO,1708108,Women Rose Gold-Toned Mirrored Analogue Watch ...,2,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
Fastrack,19280114,Men Black Brass Dial & Black Stainless Steel S...,4,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
BOLDFIT,18601682,Purple Textured Yoga Mat,3,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...",...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

##**Handling missing values**

In [12]:
csv1.dropna()#remove rows with null or empty values

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":5,""2_stars"":4,""3_stars"":13,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, A Littl...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
757,18337610,Roadster,Men Navy Blue Self-Striped Cardigan,4.3,32,2299,67.0,"""₹758.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""S"",""value"":""37.0in"",""value_name"":""Ch...","[""rw-18337610_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
760,18241294,Roadster,Women Lavender & Off White Striped Pullover,4.3,90,1699,5.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":8,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
762,18241298,Roadster,The Lifestyle Co. Women Lavender Self-Design ...,4.3,59,1999,70.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":8,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""rw-18241298_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
904,18937522,her by invictus,V-Neck Textured Regular Top,3.9,57,1298,65.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":4,""3_stars"":6,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937522_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [19]:
csv1.fillna(0)
#filling values with 0

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",0,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",0,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""pi-13698258""]",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]",0,0,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",0,Tru███m R███il,"[{""size"":""Onesize""}]",0,Sho███o. ███-10█████████enu███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",0,0,"[{""size"":""Medium""}]",0,0,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

##**4.Basic operations**

In [51]:
#filtering rows names vstar
print(csv1[csv1['title'] == 'VStar'])

    product_id  title                                product_description  \
32    18656766  VStar                            Beige Solid T-Shirt Bra
33    18656764  VStar                             Grey Solid T-Shirt Bra
54    18882294  VStar  Women White Solid Modern Fit Deep Neckline  Ca...

    rating  ratings_count  initial_price  discount final_price currency  \
32     4.6              5            345       NaN   "₹345.00"      INR
33     4.3              6            345       NaN   "₹345.00"      INR
54     4.8             10            265       NaN   "₹265.00"      INR

                                               images  ...  \
32  http://assets.myntassets.com/assets/images/186...  ...
33  http://assets.myntassets.com/assets/images/186...  ...
54  http://assets.myntassets.com/assets/images/188...  ...

                                      amount_of_stars what_customers_said  \
32  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
33  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
54  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

                 seller_name  \
32  V S███ CR███ION█████████
33  V S███ CR███ION█████████
54  V S███ CR███ION█████████

                                                sizes videos  \
32  [{"size":"30B","value":"31.5in","value_name":"...    NaN
33  [{"size":"30B","value":"31.5in","value_name":"...    NaN
54  [{"size":"XL","value":"42.0in","value_name":"T...    NaN

                                   seller_information variations  \
32  VI/███ AB███ ST█████████ODE███████████████████...        NaN
33  VI/███ AB███ ST█████████ODE███████████████████...        NaN
54  VI/███ AB███ ST█████████ODE███████████████████...        NaN

                                           best_offer  \
32  {"applicable_on":"Orders above Rs. 649 (only o...
33  {"applicable_on":"Orders above Rs. 649 (only o...
54  {"applicable_on":"Orders above Rs. 649 (only o...

                                          more_offers   category
32  [{"offer_name":"10% Instant Discount on IndusI...        bra
33  [{"offer_name":"10% Instant Discount on IndusI...        bra
54  [{"offer_name":"10% Instant Discount on IndusI...  camisoles

[3 rows x 24 columns]

In [26]:
#extracting columns
print(csv1[['title', 'rating']].head())

            title  rating
0     Lino Perros     3.8
1  Tommy Hilfiger     4.5
2           Lavie     4.4
3          F Gear     4.4
4       MYTRIDENT     4.7

In [28]:
# Remove duplicate rows
csv1 = csv1.drop_duplicates()
csv1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

##**Removing duplicates and normal forms**

In [30]:
df = pd.read_csv("Combined_dataset.csv")
df_1nf = df[[
    "product_id", "title", "product_description", "rating", "ratings_count",
    "initial_price", "discount", "final_price", "currency",
    "seller_name", "category"
]].drop_duplicates() #atomic columns only and has only product id as key thus in 2nf

df_1nf

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,seller_name,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,NaN,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,NaN,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,NaN,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,NaN,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,NaN,bath-robe
...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,NaN,watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,NaN,watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,NaN,watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,Tru███m R███il,watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,NaN,yoga-mats

In [31]:

df = df_1nf.drop_duplicates()
df
#this function removes duplicate rows after 1nf

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,seller_name,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,NaN,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,NaN,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,NaN,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,NaN,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,NaN,bath-robe
...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,NaN,watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,NaN,watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,NaN,watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,Tru███m R███il,watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,NaN,yoga-mats

##**Derived Column**

In [39]:
# Creating column by formula
df["total_amount"] = df["initial_price"] * df["ratings_count"]
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,seller_name,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,NaN,backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,NaN,backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,NaN,backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,NaN,backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,NaN,bath-robe,34788
...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,NaN,watches,130790
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,NaN,watches,195800
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,NaN,watches,39750
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,Tru███m R███il,watches,56015
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,NaN,yoga-mats,112539

##**Final code for clean dataset summarizing**

In [58]:
import pandas as pd
df1 = pd.read_csv("Combined_dataset.csv")
# keep only useful columns (converting 1nf and 2nf)
df1 = df1[[
    "product_id", "title", "product_description", "rating", "ratings_count",
    "initial_price", "discount", "final_price", "currency",
    "seller_name", "category"
]]

# fill missing values with a string
df1 = df1.fillna("Unknown")

# remove duplicates
df1 = df1.drop_duplicates()

# formula for derived column as initial price is price and ratings_count signifies quantity
df1["total_amount"] = df1["initial_price"]*df1["ratings_count"]

# exporting to csv
df1.to_csv("clean_dataset.csv")
df1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,seller_name,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,Unknown,backpacks,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,Unknown,backpacks,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,Unknown,backpacks,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,Unknown,backpacks,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,Unknown,bath-robe,34788
...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,Unknown,watches,130790
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,Unknown,watches,195800
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,Unknown,watches,39750
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,Tru███m R███il,watches,56015
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,Unknown,yoga-mats,112539